In [25]:
import torch
import torch.utils.data

In [26]:
import numpy as np
import matplotlib.pyplot as plt

In [27]:
from map_class import MapClass

In [28]:
#Training inputs for RGBcolors
rgb_colors = [[0., 0., 0.],
      [0., 0., 1.],
      [0., 0., 0.5],
      [0.125, 0.529, 1.0],
      [0.33, 0.4, 0.67],
      [0.6, 0.5, 1.0],
      [0., 1., 0.],
      [1., 0., 0.],
      [0., 1., 1.],
      [1., 0., 1.],
      [1., 1., 0.],
      [1., 1., 1.],
      [.33, .33, .33],
      [.5, .5, .5],
      [.66, .66, .66]]

In [29]:
#buildings data
building_sizes = [[0.1, 0.3], [0.1, 0.2], [1., 1.], [0.125, 0.2], [0.529, 0.12], [1.0, 0.3], [0.33, 0.3], 
                  [0.4, 0.4], [0.67, 0.3], [.33, 0.7], [.5, 0.1]]
#     torch.rand((10))

In [30]:
#gray colors data
gray_colors = [[0.1], [0.], [1.], [0.125], [0.529], [1.0], [0.33], [0.4], [0.67], [.33], [.5]]
#     torch.rand((10))

In [31]:
# Network configuration

data = rgb_colors
batch_size = 4

length = 5
width = 4
number_iterations = 100

move_closer_coef = 0.5
iterations = 100

In [32]:
trainloader = ""

def load_data(data, batch_size=4, shuffle=False):
    dim = len(data[0])
    number_rows_data = len(data)
    
    trainloader = torch.utils.data.DataLoader(data, batch_size=batch_size, shuffle=True)
    
    return trainloader, dim, number_rows_data

In [33]:
def large_cycle(map_, training_data):
    basic_visualization(map_display(map_.map))
    print(map_display(map_.map))
    for i in range(number_iterations):
        cycle(map_, training_data)
    basic_visualization(map_display(map_.map))
    print(map_display(map_.map))

In [34]:
training, dim, number_rows_data = load_data(data)

In [19]:
map1 = MapClass(length, width, dim, move_closer_coef)

0 0
0 1
0 2
0 3
1 0
1 1
1 2
1 3
2 0
2 1
2 2
2 3
3 0
3 1
3 2
3 3
4 0
4 1
4 2
4 3


In [20]:
map1.weights

tensor([[0.5719, 0.9141, 0.8983],
        [0.4812, 0.3555, 0.7058],
        [0.8213, 0.6953, 0.0184],
        [0.0414, 0.1167, 0.5105],
        [0.0697, 0.5362, 0.6414],
        [0.0670, 0.1117, 0.6999],
        [0.3598, 0.9983, 0.0603],
        [0.1573, 0.6363, 0.4592],
        [0.3304, 0.1620, 0.9275],
        [0.1613, 0.3365, 0.1567],
        [0.2105, 0.7417, 0.9140],
        [0.5918, 0.5133, 0.0165],
        [0.6007, 0.5924, 0.4603],
        [0.5804, 0.0448, 0.5066],
        [0.9087, 0.7218, 0.9672],
        [0.5117, 0.5139, 0.9913],
        [0.4546, 0.1633, 0.3515],
        [0.4247, 0.1723, 0.6231],
        [0.1171, 0.1745, 0.7418],
        [0.9848, 0.1053, 0.6398]])

In [21]:
map1.cycle(training)

In [22]:
map1.weights

tensor([[0.2749, 0.6781, 0.6846],
        [0.2665, 0.6082, 0.5317],
        [0.2484, 0.6080, 0.3617],
        [0.2124, 0.4509, 0.3111],
        [0.3861, 0.5977, 0.7290],
        [0.3493, 0.5465, 0.6454],
        [0.3201, 0.5135, 0.5212],
        [0.2968, 0.4360, 0.4377],
        [0.5105, 0.5563, 0.8231],
        [0.4463, 0.5083, 0.7542],
        [0.3790, 0.4430, 0.6749],
        [0.3678, 0.3644, 0.5333],
        [0.5868, 0.5558, 0.8969],
        [0.4861, 0.4593, 0.8335],
        [0.4125, 0.3831, 0.7776],
        [0.3857, 0.3211, 0.6835],
        [0.5380, 0.4855, 0.8273],
        [0.4566, 0.3978, 0.8399],
        [0.3279, 0.2678, 0.8428],
        [0.4624, 0.2294, 0.7451]])

In [23]:
map1.distance_matrix

tensor([[0.0000, 1.0000, 2.0000, 3.0000, 1.0000, 1.4142, 2.2361, 3.1623, 2.0000,
         2.2361, 2.8284, 3.6056, 3.0000, 3.1623, 3.6056, 4.2426, 4.0000, 4.1231,
         4.4721, 5.0000],
        [1.0000, 0.0000, 1.0000, 2.0000, 1.4142, 1.0000, 1.4142, 2.2361, 2.2361,
         2.0000, 2.2361, 2.8284, 3.1623, 3.0000, 3.1623, 3.6056, 4.1231, 4.0000,
         4.1231, 4.4721],
        [2.0000, 1.0000, 0.0000, 1.0000, 2.2361, 1.4142, 1.0000, 1.4142, 2.8284,
         2.2361, 2.0000, 2.2361, 3.6056, 3.1623, 3.0000, 3.1623, 4.4721, 4.1231,
         4.0000, 4.1231],
        [3.0000, 2.0000, 1.0000, 0.0000, 3.1623, 2.2361, 1.4142, 1.0000, 3.6056,
         2.8284, 2.2361, 2.0000, 4.2426, 3.6056, 3.1623, 3.0000, 5.0000, 4.4721,
         4.1231, 4.0000],
        [1.0000, 1.4142, 2.2361, 3.1623, 0.0000, 1.0000, 2.0000, 3.0000, 1.0000,
         1.4142, 2.2361, 3.1623, 2.0000, 2.2361, 2.8284, 3.6056, 3.0000, 3.1623,
         3.6056, 4.2426],
        [1.4142, 1.0000, 1.4142, 2.2361, 1.0000, 0.0000, 1.0

In [24]:
map1.impact_matrix

tensor([[1.0000, 0.6892, 0.4237, 0.2301, 0.6892, 0.5716, 0.3711, 0.2059, 0.4237,
         0.3711, 0.2579, 0.1492, 0.2301, 0.2059, 0.1492, 0.0897, 0.1096, 0.0991,
         0.0736, 0.0455],
        [0.6892, 1.0000, 0.6892, 0.4237, 0.5716, 0.6892, 0.5716, 0.3711, 0.3711,
         0.4237, 0.3711, 0.2579, 0.2059, 0.2301, 0.2059, 0.1492, 0.0991, 0.1096,
         0.0991, 0.0736],
        [0.4237, 0.6892, 1.0000, 0.6892, 0.3711, 0.5716, 0.6892, 0.5716, 0.2579,
         0.3711, 0.4237, 0.3711, 0.1492, 0.2059, 0.2301, 0.2059, 0.0736, 0.0991,
         0.1096, 0.0991],
        [0.2301, 0.4237, 0.6892, 1.0000, 0.2059, 0.3711, 0.5716, 0.6892, 0.1492,
         0.2579, 0.3711, 0.4237, 0.0897, 0.1492, 0.2059, 0.2301, 0.0455, 0.0736,
         0.0991, 0.1096],
        [0.6892, 0.5716, 0.3711, 0.2059, 1.0000, 0.6892, 0.4237, 0.2301, 0.6892,
         0.5716, 0.3711, 0.2059, 0.4237, 0.3711, 0.2579, 0.1492, 0.2301, 0.2059,
         0.1492, 0.0897],
        [0.5716, 0.6892, 0.5716, 0.3711, 0.6892, 1.0000, 0.6

In [17]:
basic_visualization(map1.map)

NameError: name 'basic_visualization' is not defined