In [1]:
import torch
import torch.utils.data

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from map_class import MapClass

In [4]:
#Training inputs for RGBcolors
rgb_colors = [[0., 0., 0.],
      [0., 0., 1.],
      [0., 0., 0.5],
      [0.125, 0.529, 1.0],
      [0.33, 0.4, 0.67],
      [0.6, 0.5, 1.0],
      [0., 1., 0.],
      [1., 0., 0.],
      [0., 1., 1.],
      [1., 0., 1.],
      [1., 1., 0.],
      [1., 1., 1.],
      [.33, .33, .33],
      [.5, .5, .5],
      [.66, .66, .66]]

In [5]:
#buildings data
building_sizes = [[0.1, 0.3], [0.1, 0.2], [1., 1.], [0.125, 0.2], [0.529, 0.12], [1.0, 0.3], [0.33, 0.3], 
                  [0.4, 0.4], [0.67, 0.3], [.33, 0.7], [.5, 0.1]]
#     torch.rand((10))

In [6]:
#gray colors data
gray_colors = [[0.1], [0.], [1.], [0.125], [0.529], [1.0], [0.33], [0.4], [0.67], [.33], [.5]]
#     torch.rand((10))

In [7]:
# Network configuration

data = rgb_colors
batch_size = 4

length = 5
width = 4
number_iterations = 100

move_closer_coef = 0.5
iterations = 100

In [8]:
def basic_visualization(map_):
    plt.imshow(map_);
    plt.colorbar()
    plt.show()

In [9]:
trainloader = ""

def load_data(data, batch_size=4, shuffle=False):
    global dim
    dim = len(data[0])
    
    trainloader = torch.utils.data.DataLoader(data, batch_size=batch_size, shuffle=True)
    
    return trainloader

In [10]:
def map_view_for_coding(map_):
    return torch.transpose(map_, 0, 1).view(dim, length, width)
#     return map_.view(dim, length, width)

In [11]:
def map_display(map_):
#     return torch.transpose(map_, 0, 1).view(dim, length, width)
    if dim == 1:
        return map_.view(length, width)
    else:
        return map_.view(dim, length, width)

In [12]:
def large_cycle(map_, training_data):
    basic_visualization(map_display(map_.map))
    print(map_display(map_.map))
    for i in range(number_iterations):
        cycle(map_, training_data)
    basic_visualization(map_display(map_.map))
    print(map_display(map_.map))

In [13]:
training = load_data(data)

In [14]:
map1 = MapClass(length, width, dim, move_closer_coef)

0 0
0 1
0 2
0 3
1 0
1 1
1 2
1 3
2 0
2 1
2 2
2 3
3 0
3 1
3 2
3 3
4 0
4 1
4 2
4 3


In [16]:
map1.weights

tensor([[0.1785, 0.0531, 0.4577],
        [0.6640, 0.6540, 0.5780],
        [0.5968, 0.0095, 0.9332],
        [0.2332, 0.4453, 0.7171],
        [0.7372, 0.7276, 0.0724],
        [0.0046, 0.4682, 0.8847],
        [0.2088, 0.1948, 0.2633],
        [0.8950, 0.4848, 0.4366],
        [0.9254, 0.9905, 0.1223],
        [0.0709, 0.6832, 0.9384],
        [0.6987, 0.9392, 0.6075],
        [0.2175, 0.7030, 0.1115],
        [0.5843, 0.6916, 0.5062],
        [0.4384, 0.6011, 0.1284],
        [0.0847, 0.0787, 0.2489],
        [0.7483, 0.9382, 0.6216],
        [0.9610, 0.5997, 0.0376],
        [0.0488, 0.8153, 0.9248],
        [0.9190, 0.0555, 0.0608],
        [0.0866, 0.1030, 0.8092]])

In [17]:
map1.cycle(training)

In [18]:
map1.weights

tensor([[0.0892, 0.0266, 0.4789],
        [0.6460, 0.6185, 0.7245],
        [0.7984, 0.0048, 0.9666],
        [0.2816, 0.4227, 0.6935],
        [0.7372, 0.7276, 0.0724],
        [0.0046, 0.4682, 0.8847],
        [0.2694, 0.2624, 0.2967],
        [0.8950, 0.4848, 0.4366],
        [0.9627, 0.9953, 0.0611],
        [0.0979, 0.6061, 0.9692],
        [0.6987, 0.9392, 0.6075],
        [0.1087, 0.8515, 0.0558],
        [0.5421, 0.5958, 0.5031],
        [0.4384, 0.6011, 0.1284],
        [0.0423, 0.0394, 0.1245],
        [0.8741, 0.9691, 0.8108],
        [0.9610, 0.5997, 0.0376],
        [0.0244, 0.9076, 0.9624],
        [0.9595, 0.0277, 0.0304],
        [0.0433, 0.0515, 0.9046]])

In [19]:
map1.distance_matrix

tensor([[0.0000, 1.0000, 2.0000, 3.0000, 1.0000, 1.4142, 2.2361, 3.1623, 2.0000,
         2.2361, 2.8284, 3.6056, 3.0000, 3.1623, 3.6056, 4.2426, 4.0000, 4.1231,
         4.4721, 5.0000],
        [1.0000, 0.0000, 1.0000, 2.0000, 1.4142, 1.0000, 1.4142, 2.2361, 2.2361,
         2.0000, 2.2361, 2.8284, 3.1623, 3.0000, 3.1623, 3.6056, 4.1231, 4.0000,
         4.1231, 4.4721],
        [2.0000, 1.0000, 0.0000, 1.0000, 2.2361, 1.4142, 1.0000, 1.4142, 2.8284,
         2.2361, 2.0000, 2.2361, 3.6056, 3.1623, 3.0000, 3.1623, 4.4721, 4.1231,
         4.0000, 4.1231],
        [3.0000, 2.0000, 1.0000, 0.0000, 3.1623, 2.2361, 1.4142, 1.0000, 3.6056,
         2.8284, 2.2361, 2.0000, 4.2426, 3.6056, 3.1623, 3.0000, 5.0000, 4.4721,
         4.1231, 4.0000],
        [1.0000, 1.4142, 2.2361, 3.1623, 0.0000, 1.0000, 2.0000, 3.0000, 1.0000,
         1.4142, 2.2361, 3.1623, 2.0000, 2.2361, 2.8284, 3.6056, 3.0000, 3.1623,
         3.6056, 4.2426],
        [1.4142, 1.0000, 1.4142, 2.2361, 1.0000, 0.0000, 1.0

In [20]:
map1.impact_matrix

tensor([[1.0000, 0.6892, 0.4237, 0.2301, 0.6892, 0.5716, 0.3711, 0.2059, 0.4237,
         0.3711, 0.2579, 0.1492, 0.2301, 0.2059, 0.1492, 0.0897, 0.1096, 0.0991,
         0.0736, 0.0455],
        [0.6892, 1.0000, 0.6892, 0.4237, 0.5716, 0.6892, 0.5716, 0.3711, 0.3711,
         0.4237, 0.3711, 0.2579, 0.2059, 0.2301, 0.2059, 0.1492, 0.0991, 0.1096,
         0.0991, 0.0736],
        [0.4237, 0.6892, 1.0000, 0.6892, 0.3711, 0.5716, 0.6892, 0.5716, 0.2579,
         0.3711, 0.4237, 0.3711, 0.1492, 0.2059, 0.2301, 0.2059, 0.0736, 0.0991,
         0.1096, 0.0991],
        [0.2301, 0.4237, 0.6892, 1.0000, 0.2059, 0.3711, 0.5716, 0.6892, 0.1492,
         0.2579, 0.3711, 0.4237, 0.0897, 0.1492, 0.2059, 0.2301, 0.0455, 0.0736,
         0.0991, 0.1096],
        [0.6892, 0.5716, 0.3711, 0.2059, 1.0000, 0.6892, 0.4237, 0.2301, 0.6892,
         0.5716, 0.3711, 0.2059, 0.4237, 0.3711, 0.2579, 0.1492, 0.2301, 0.2059,
         0.1492, 0.0897],
        [0.5716, 0.6892, 0.5716, 0.3711, 0.6892, 1.0000, 0.6

In [21]:
basic_visualization(map1.map)

AttributeError: 'MapClass' object has no attribute 'map'