In [1]:
import torch

In [2]:
from map_class import MapClass

In [3]:
#gray colors data
gray_colors = [[0.1], [0.], [1.], [0.125], [0.529], [1.0], [0.33], [0.4], [0.67], [.33], [.5]]
#     torch.rand((10))

In [4]:
gray_colors

[[0.1],
 [0.0],
 [1.0],
 [0.125],
 [0.529],
 [1.0],
 [0.33],
 [0.4],
 [0.67],
 [0.33],
 [0.5]]

In [5]:
def convert_data(data):
    tensor_data = []
    for row in data:
        tensor_data.append(torch.FloatTensor(row))
    
    return tensor_data

In [6]:
# Network configuration
length = 4
width = 3
number_iterations = 100

input_data = convert_data(gray_colors)


move_closer_coef = 0.5

# if len(input_data[0]) == 1:
#     dim = 1
# else:
dim = len(input_data[0])

In [7]:
input_data[0].shape

torch.Size([1])

In [8]:
torch.FloatTensor([0., 0., 1.])

tensor([0., 0., 1.])

In [9]:
map1 = MapClass(length, width, dim, move_closer_coef)

In [10]:
map1.map

tensor([[0.4998],
        [0.5631],
        [0.1886],
        [0.2676],
        [0.2389],
        [0.2442],
        [0.2161],
        [0.8708],
        [0.9648],
        [0.4636],
        [0.9268],
        [0.7759]])

In [11]:
map1.map

tensor([[0.4998],
        [0.5631],
        [0.1886],
        [0.2676],
        [0.2389],
        [0.2442],
        [0.2161],
        [0.8708],
        [0.9648],
        [0.4636],
        [0.9268],
        [0.7759]])

In [12]:
map1.find_bmu(input_data[0])

tensor([[2]])

In [13]:
map1.map[5]

tensor([0.2442])

In [14]:
input_data[0]

tensor([0.1000])

In [15]:
change = map1.map[5] - input_data[0]

In [16]:
map1.map[5] = map1.map[5] - (change * move_closer_coef)

In [17]:
map1.map

tensor([[0.4998],
        [0.5631],
        [0.1886],
        [0.2676],
        [0.2389],
        [0.1721],
        [0.2161],
        [0.8708],
        [0.9648],
        [0.4636],
        [0.9268],
        [0.7759]])

In [18]:
map1.move_closer(0, input_data[0])

In [19]:
map1

tensor([[0.2999],
        [0.5631],
        [0.1886],
        [0.2676],
        [0.2389],
        [0.1721],
        [0.2161],
        [0.8708],
        [0.9648],
        [0.4636],
        [0.9268],
        [0.7759]])