In [1]:
import torch

In [2]:
from map_class import MapClass

In [3]:
#gray colors data
gray_colors = [[0.], [0.], [1.], [0.125], [0.529], [1.0], [0.33], [0.4], [0.67], [.33], [.5]]
#     torch.rand((10))

In [4]:
gray_colors

[[0.0],
 [0.0],
 [1.0],
 [0.125],
 [0.529],
 [1.0],
 [0.33],
 [0.4],
 [0.67],
 [0.33],
 [0.5]]

In [5]:
def convert_data(data):
    tensor_data = []
    for row in data:
        tensor_data.append(torch.FloatTensor(row))
    
    return tensor_data

In [6]:
# Network configuration
length = 4
width = 3
number_iterations = 100

input_data = convert_data(gray_colors)


# if len(input_data[0]) == 1:
#     dim = 1
# else:
dim = len(input_data[0])

In [7]:
input_data[0].shape

torch.Size([1])

In [8]:
torch.FloatTensor([0., 0., 1.])

tensor([0., 0., 1.])

In [9]:
map1 = MapClass(length, width, dim)

In [22]:
map1.find_bmu(input_data[0])[1]

tensor([[11]])

In [19]:
map1.map

tensor([[0.8523],
        [0.8107],
        [0.8288],
        [0.5368],
        [0.9166],
        [0.2939],
        [0.4178],
        [0.8986],
        [0.3390],
        [0.3971],
        [0.3805],
        [0.2348]])

In [12]:
wyliczone = (map1.map - input_data[0]).pow(2)
wyliczone

tensor([[0.7264],
        [0.6572],
        [0.6870],
        [0.2882],
        [0.8401],
        [0.0863],
        [0.1746],
        [0.8075],
        [0.1149],
        [0.1577],
        [0.1448],
        [0.0551]])

In [13]:
torch.topk(wyliczone, 1, dim=0, largest=False)

torch.return_types.topk(
values=tensor([[0.0551]]),
indices=tensor([[11]]))

In [14]:
map1.get_location(7)

2 1


In [15]:
12/3

4.0

In [16]:
12%3

0

In [17]:
def get_location(number):
    row = "dupa"
    column = "dupa2"

    # if x%width == 0:
    row = int((x/width))
    column = x - (row * width)



    print(row, column)

In [18]:
x = 4
row = "dupa"
column = "dupa2"

# if x%width == 0:
row = int((x/width))
column = x - (row * width)

    
    
print(row, column)

1 1
