In [1]:
import torch

In [2]:
from map_class import MapClass

In [3]:
#buildings data
building_sizes = [[0.1, 0.3], [0.1, 0.2], [1., 1.], [0.125, 0.2], [0.529, 0.12], [1.0, 0.3], [0.33, 0.3], 
                  [0.4, 0.4], [0.67, 0.3], [.33, 0.7], [.5, 0.1]]
#     torch.rand((10))

In [4]:
#gray colors data
gray_colors = [[0.1], [0.], [1.], [0.125], [0.529], [1.0], [0.33], [0.4], [0.67], [.33], [.5]]
#     torch.rand((10))

In [7]:
def convert_data(data):
    tensor_data = []
    for row in data:
        tensor_data.append(torch.FloatTensor(row))
    
    return tensor_data

In [25]:
def map_view(map_):
    return map_.view(dim, length, width)

In [33]:
# Network configuration
length = 4
width = 3
number_iterations = 100

input_data = convert_data(building_sizes)


move_closer_coef = 0.5

# if len(input_data[0]) == 1:
#     dim = 1
# else:
dim = len(input_data[0])

In [34]:
def cycle(map_, input_data):
    for row in input_data:
        i_bmu = map1.find_bmu(row).item()
        map_.move_closer(i_bmu, row)
        
    print(map_view(map_.map))
        

In [30]:
map1 = MapClass(length, width, dim, move_closer_coef)

In [31]:
map_view(map1.map)

tensor([[[0.6616, 0.6704, 0.4361],
         [0.1063, 0.3697, 0.3028],
         [0.4217, 0.9711, 0.3186],
         [0.5138, 0.2620, 0.6215]]])

In [32]:
cycle(map1, input_data)

tensor([[[0.6616, 0.6702, 0.4361],
         [0.0883, 0.3697, 0.3028],
         [0.4108, 0.9928, 0.3271],
         [0.5107, 0.2620, 0.6215]]])


In [16]:
input_data[0]

tensor([0.1000])

In [18]:
map1.find_bmu(input_data[0]).item()

3

In [19]:
map1.move_closer(3, input_data[0])

In [20]:
map_view(map1.map)

tensor([[[0.8615, 0.6281, 0.0090],
         [0.1001, 0.8868, 0.8063],
         [0.2009, 0.9625, 0.3780],
         [0.5537, 0.8250, 0.2976]]])

In [21]:
input_data[1]

tensor([0.])

In [22]:
map1.find_bmu(input_data[1])

tensor([[2]])

In [23]:
map1.move_closer(2, input_data[1])

In [24]:
map_view(map1.map)

tensor([[[0.8615, 0.6281, 0.0045],
         [0.1001, 0.8868, 0.8063],
         [0.2009, 0.9625, 0.3780],
         [0.5537, 0.8250, 0.2976]]])

In [8]:
torch.FloatTensor([0., 0., 1.])

tensor([0., 0., 1.])

In [9]:
map1 = MapClass(length, width, dim, move_closer_coef)

In [10]:
map1.map

tensor([[0.4998],
        [0.5631],
        [0.1886],
        [0.2676],
        [0.2389],
        [0.2442],
        [0.2161],
        [0.8708],
        [0.9648],
        [0.4636],
        [0.9268],
        [0.7759]])

In [11]:
map1.map

tensor([[0.4998],
        [0.5631],
        [0.1886],
        [0.2676],
        [0.2389],
        [0.2442],
        [0.2161],
        [0.8708],
        [0.9648],
        [0.4636],
        [0.9268],
        [0.7759]])

In [12]:
map1.find_bmu(input_data[0])

tensor([[2]])

In [13]:
map1.map[5]

tensor([0.2442])

In [14]:
input_data[0]

tensor([0.1000])

In [15]:
change = map1.map[5] - input_data[0]

In [16]:
map1.map[5] = map1.map[5] - (change * move_closer_coef)

In [17]:
map1.map

tensor([[0.4998],
        [0.5631],
        [0.1886],
        [0.2676],
        [0.2389],
        [0.1721],
        [0.2161],
        [0.8708],
        [0.9648],
        [0.4636],
        [0.9268],
        [0.7759]])

In [18]:
map1.move_closer(0, input_data[0])

In [19]:
map1

tensor([[0.2999],
        [0.5631],
        [0.1886],
        [0.2676],
        [0.2389],
        [0.1721],
        [0.2161],
        [0.8708],
        [0.9648],
        [0.4636],
        [0.9268],
        [0.7759]])