In [ ]:
torch.FloatTensor([0., 0., 1.])

In [ ]:
map1 = MapClass(length, width, dim, move_closer_coef)

In [ ]:
map1.map

In [ ]:
map1.map

In [ ]:
map1.find_bmu(input_data[0])

In [ ]:
map1.map[5]

In [ ]:
input_data[0]

In [ ]:
change = map1.map[5] - input_data[0]

In [ ]:
map1.map[5] = map1.map[5] - (change * move_closer_coef)

In [ ]:
map1.map

In [ ]:
map1.move_closer(0, input_data[0])

In [ ]:
map1

In [14]:
input_data[0]

tensor([0.1000, 0.3000])

In [15]:
map2 = MapClass(length, width, dim, move_closer_coef)

In [16]:
map_view(map2.map)

tensor([[[0.9904, 0.7310, 0.0053],
         [0.2924, 0.1835, 0.6877],
         [0.7551, 0.2119, 0.5439],
         [0.3339, 0.3394, 0.6527]],

        [[0.6395, 0.6590, 0.3164],
         [0.8398, 0.5236, 0.7563],
         [0.5196, 0.9123, 0.5672],
         [0.1545, 0.9025, 0.8709]]])

In [17]:
for i in range(11):
    print((map2.map[i] - input_data[0]).pow(2))

tensor([0.7928, 0.1152])
tensor([0.3981, 0.1289])
tensor([0.0090, 0.0003])
tensor([0.0370, 0.2914])
tensor([0.0070, 0.0500])
tensor([0.3454, 0.2082])
tensor([0.4292, 0.0482])
tensor([0.0125, 0.3749])
tensor([0.1971, 0.0714])
tensor([0.0547, 0.0212])
tensor([0.0573, 0.3630])


In [18]:
for i in range(11):
    print(sum((map2.map[i] - input_data[0]).pow(2)))

tensor(0.9080)
tensor(0.5270)
tensor(0.0092)
tensor(0.3284)
tensor(0.0570)
tensor(0.5536)
tensor(0.4774)
tensor(0.3874)
tensor(0.2685)
tensor(0.0759)
tensor(0.4203)


In [19]:
map2.find_bmu(input_data[0])

tensor([[7.9280e-01, 1.1523e-01],
        [3.9810e-01, 1.2891e-01],
        [8.9715e-03, 2.7027e-04],
        [3.7031e-02, 2.9137e-01],
        [6.9751e-03, 4.9990e-02],
        [3.4539e-01, 2.0820e-01],
        [4.2919e-01, 4.8208e-02],
        [1.2524e-02, 3.7491e-01],
        [1.9706e-01, 7.1418e-02],
        [5.4710e-02, 2.1183e-02],
        [5.7293e-02, 3.6303e-01],
        [3.0544e-01, 3.2596e-01]])
tensor([0.9080, 0.5270, 0.0092, 0.3284, 0.0570, 0.5536, 0.4774, 0.3874, 0.2685,
        0.0759, 0.4203, 0.6314])
torch.return_types.topk(
values=tensor([0.0092]),
indices=tensor([2]))


tensor([2])

In [ ]:
map1.move_closer(3, input_data[0])

In [ ]:
map_view(map1.map)

In [ ]:
input_data[1]

In [ ]:
map1.find_bmu(input_data[1])

In [ ]:
map1.move_closer(2, input_data[1])

In [ ]:
map_view(map1.map)